ALTER TABLE SOE.TLOGS DROP PRIMARY KEY;
DROP INDEX SOE.TLOGS_HINDEX;
DROP TABLESPACE SOE2 INCLUDING CONTENTS AND DATAFILES;
DROP SEQUENCE SOE.S;
ALTER SYSTEM FLUSH BUFFER_CACHE;


CREATE TABLESPACE SOE2;
ALTER USER SOE QUOTA UNLIMITED ON SOE2;

CONN soe/soe@RAC

TRUNCATE TABLE TLOGS;

CREATE UNIQUE INDEX TLOGS_HINDEX ON TLOGS (ROW_ID) GLOBAL
 PARTITION BY HASH (ROW_ID)
   (PARTITION P1  TABLESPACE SOE,
    PARTITION P2  TABLESPACE SOE2);

CREATE SEQUENCE S
      INCREMENT BY 1
      START WITH 1
      NOMAXVALUE
      NOCYCLE
      CACHE 1000;

exit