-- retrieve the top wait events of the sessions and the average wait time for each session on the event:
col wait_class format a14
col event format a35
col OBJECT_NAME format a10

SELECT WAIT_CLASS, EVENT,  OBJECT_NAME, TO_CHAR(ROUND(AVERAGE_TIME,2),'999,999,999.99') AVERAGE_TIME 
FROM (
 SELECT WAIT_CLASS, EVENT,  (select object_name from dba_objects where OBJECT_ID=CURRENT_OBJ#) OBJECT_NAME , AVG(TIME_WAITED) AVERAGE_TIME
 FROM GV$ACTIVE_SESSION_HISTORY 
 WHERE
  SAMPLE_TIME BETWEEN TO_DATE('&&BEGIN_TIME','DD-MM-YY HH24:MI:SS') AND TO_DATE('&&END_TIME','DD-MM-YY HH24:MI:SS')
 AND 
  USER_ID = (SELECT USER_ID FROM DBA_USERS WHERE USERNAME='SOE')
 AND EVENT IS NOT NULL
 GROUP BY WAIT_CLASS, EVENT,CURRENT_OBJ#
 ORDER BY AVG(TIME_WAITED) DESC 
 )
  WHERE ROWNUM <= 10
;


SELECT TO_CHAR(ROUND(SUM(AVERAGE_TIME),2),'999,999,999.99') TOTAL_WAIT
FROM (
 SELECT WAIT_CLASS, EVENT,  (select object_name from dba_objects where OBJECT_ID=CURRENT_OBJ#) OBJECT_NAME , AVG(TIME_WAITED) AVERAGE_TIME
 FROM GV$ACTIVE_SESSION_HISTORY 
 WHERE
  SAMPLE_TIME BETWEEN TO_DATE('&BEGIN_TIME','DD-MM-YY HH24:MI:SS') AND TO_DATE('&END_TIME','DD-MM-YY HH24:MI:SS')
 AND 
  USER_ID = (SELECT USER_ID FROM DBA_USERS WHERE USERNAME='SOE')
 AND EVENT IS NOT NULL
 GROUP BY WAIT_CLASS, EVENT,CURRENT_OBJ#
 ORDER BY AVG(TIME_WAITED) DESC 
 )
  WHERE ROWNUM <= 10
;

exit




